### ISSUE TITLE
Does Sidecloq know to handle multiple processes running sidekiq?

### ISSUE THREAD

**Issue by dbenjamin57** [mattyr/sidecloq#12]

**Comment by mattyr** [comment]
In what regards?  One core reason sidecloq was built was to handle scenarios where you are running multiple sidekiq instances, but only want a single scheduling process running with automated failover.  Do you mean something else?  Describe your scenario and I'll let you know if sidecloq is a good fit.

**Comment by dbenjamin57** [comment]
Hey Matt, thanks for your response.

We are running hundreds of servers which are the same (docker + Kubernetes). With this architecture, all our Sidekiq servers will have Sidecloq. 

We also have multiple projects running different code-bases (each with sidekiq and potentially sidecloq) but sharing redis, as Redis is the message queue system between the different components we have. 

Up until now we were using Sidetiq but it became incompatible with current Sidekiq.

**Comment by mattyr** [comment]
Cool, so sidecloq was made was for that scale -- my assumption is that the application is shared on all of those servers.  Sidecloq will run an instance on all of the sidekiq servers, but all except one will just be in a holding pattern (basically taking 0 resources, just occasionally checking redis).  The one operational sidecloq worker will queue jobs, but if it ever fails, one of the others will automatically take it's place (automatic failover).

As far as "sharing" redis -- sidecloq uses sidekiq's connection pool, so if you namespace your sidekiq instances, sidecloq will follow suit.  sidecloq will maintain a single "working" instance per namespace.

If you wanted, could push failover responsibilities to kubernetes, and just configure particular sidekiq instances to run sidecloq.

Hope that helps!

**Comment by dbenjamin57** [comment]
Hey Matt, can you elaborate regarding the namespace? If these are completely different projects, they should be in a different namespace by default, no?

**Comment by mattyr** [comment]
Sorry, *redis* namespaces, not namespaces in code.  If you have separate applications using the same redis instance, you have the possibility of one overwriting the other's values if they happen to use the same keys.  redis namespaces is one way to address that.  (though honestly, redis is so cheap to run and if you're using kubernetes it's easy enough to just spin up separate instances per-app, which might even be the preferred way of doing things...(

**Comment by dbenjamin57** [comment]
Running separate Redises is not an option for us... We use Redis as a message queue between our different components (through sidekiq)... 

So essentially you're saying that without Redis namespaces, I'll only have an elected leader for a single project but not for all of them if they share the same redis. correct?

**Comment by mattyr** [comment]
You'll have an elected leader per redis namespace.  So you could mix and match that with your projects as needed.  However, I don't think it makes sense to have multiple projects running a single schedule -- you'd have to maintain the same configuration across projects otherwise you'll end up with one schedule clobbering another.  .. but that's just my opinion!

Feel free to re-open if you have more questions!
