### ISSUE TITLE
Require activesupport

### ISSUE THREAD

**Issue by stmllr** [mattyr/sidecloq#20]
JobEnquer uses String method [`constantize`](https://github.com/mattyr/sidecloq/blob/master/lib/sidecloq/job_enqueuer.rb#L8) from gem "activesupport", however this dependency is missing in Gemfile.

Non-rails projects fail with   
```
["error enqueuing example_job - NoMethodError: undefined method `constantize' for \"My::ExampleWorker\":String"]
```

I propose to add "activesupport" to Gemfile and use `require "active_support/core_ext/string"` in JobEnquer.

**Comment by stmllr** [comment]
If `constantize` is the only feature used from activesupport, I'd rather implement this instead of using activesupport.

**Comment by mattyr** [comment]
That's an excellent idea!  Feel free to send over a pull request; or I can take a look sometime soon.

**Comment by stmllr** [comment]
There you go.
