### ISSUE TITLE
Redlock has released 1.0.0

### ISSUE THREAD

**Issue by krainboltgreene** [mattyr/sidecloq#23]

**Comment by mattyr** [comment]
Thanks for the heads up!

Just release 0.4.5 that loosens the redlock dependency.

**Comment by krainboltgreene** [comment]
Gracias. Doesn't look like there was any breaking change. I'll try it out!

Also, any reason to not release 1.0.0?

**Comment by mattyr** [comment]
i like the flexibility implied by being pre-1.0.0; i'm still willing to take feedback and make changes to the public api/etc.  i'd like to strip out some dependencies before making it 1.0.0, too.  is there a reason you'd like a 1.0.0?

**Comment by krainboltgreene** [comment]
Just in case you didn't know this, you can still take feedback, make
breaking changes, and be flexible after 1.0.0. You just hump the version
after.

**Comment by mattyr** [comment]
of course -- i think there is greater implied flexibility prior to a 1.0.0, but you are correct.

my question for you is basically along the same lines -- is there a reason that you'd like to see a 1.0.0?  i don't currently have any reasons to release a 1.0.0 myself, but i'm totally open to others' ideas/opinions.

**Comment by krainboltgreene** [comment]
You've got people using your software in production my friend! This thing
is ready for that proud label. Plus, it's suggested in the semantic version
faq.

**Comment by mattyr** [comment]
Excellent points.

Two things I'd like to do prior to 1.0.0:

- Limit the matrix of ruby/sidekiq version support
- Take care of this: #1 (and any other easy remove-heavy-dependency stuff possible)

I assume you're using this in production (I certainly am, across several projects for many years now!).  Can you let me know what kind of environment it's running in?  Any info would be great, like ruby versions, sidekiq versions, platform, hosting service/etc.  There's not a large, vocal community behind this project, so most of the decisions have been made based on my own use-cases.

Thanks!

**Comment by krainboltgreene** [comment]
I'll get that information by EOD.
