### ISSUE TITLE
Tag logs with some identifier

### ISSUE THREAD

**Issue by krainboltgreene** [mattyr/sidecloq#26]
I often see "Leader lock held" in my logs, but no indicator from where it came. It would be great if sidecloq used a log tag of like: `logger.tagged("Sidecloq") { logger.info("Leader lock held") }`.

**Comment by krainboltgreene** [comment]
Also, that specific log should probably be debug?

**Comment by mattyr** [comment]
So we're leveraging Sidekiq's logging functionality, which includes the ability to add context to the log messages -- we're using the context "Sidecloq":

https://github.com/mattyr/sidecloq/blob/e25c366dac3dc2bb097983ac63507ad62f2bb4ab/lib/sidecloq/utils.rb#L6-L20

Is that the only Sidecloq log message you're seeing without the "Sidecloq" context?

**Comment by mattyr** [comment]
Oh, and I think "tagged" is an ActiveSupport logging extension, and we removed our dependency on ActiveSupport a ways back (in an effort to stay lightweight depency-wise).

**Comment by krainboltgreene** [comment]
It's a part of AS currently. All of sidecloq's messages are plain for me.
We're pointing sidekiqs logger to Rails.logger. I guess the UI I'm using is
only showing the message part, so that is probably the issue.

**Comment by krainboltgreene** [comment]
Looks like our logging logic is losing the context, so this isn't sidecloq's fault.
