### ISSUE TITLE
Sidecloq not working with Redis ConnectionPool

### ISSUE THREAD

**Issue by tbem** [mattyr/sidecloq#33]
I'm trying to configure sidecloq in a project with ConnectionPool for client and server configured like: 

Sidekiq.configure_client do |config|
  config.redis =  ConnectionPool.new(size: 5, &redis_conn)
  Sidekiq::Status.configure_client_middleware config, expiration: 1.month
end

Looking for logs, sidecloq can´t get the leader lock. It stucks there after creating the new Thread. 

Any thoughts on this?

Regards!

**Comment by mattyr** [comment]
Hmm... looks like the way we have obtain a connection is via Sidekiq's default redis_pool, which can cause issues if the Sidekiq is configured using a custom pool (as you have above).  I can see two options:

- We can fix Sidecloq to use the redis connection in the same way as Sidekiq (I'd need to see if there are other variations on the configuration that we'd need to support)
- We can make it so Sidecloq accepts it's own redis connection option for the locker (this would allow complete control)

Any thoughts or preferences?  I think both would be good to do, but maybe we can focus on what you need first.

**Comment by mattyr** [comment]
I just took a second look at the code -- there actually is already a way to specifically configure the redis connection for Sidecloq!  In your configure block, you can do:

```ruby
Sidecloq.configure do |config|
  config[:redis] = "redis://127.0.0.1:7777"
end
```

You can also pass a reference to a more specifically-configured redis connection, ie:

```ruby
Sidecloq.configure do |config|
  config[:redis] = Redis.new(:url => 'redis://someotherhost:6379')
end
```

Let me know if that works for you... Let's still keep this issue open regardless, because I'd like Sidecloq to be able to automatically use the Sidekiq redis connection configuration, even when using a connection pool.  Also makes sense to update the readme with details on how to customize the redis connection.

**Comment by tbem** [comment]
Hi Matt, 
IMHO what makes more sense is to let sidecloq  use the connection settings from sidekiq, it's simpler to end user, and don't need extra config. Once it's not working right now, i'll test the config you suggested and i'll give feedback latter. 
IMHO the option for sidecloq accepting a connection just for the locker don't look elegant, it's more like a hack to solve the problem. 
Thanks for the feedback, i can't test it right now, but hope until the end of the day provide some more feedback. Regards!

**Comment by mattyr** [comment]
I agree that using the sidekiq redis configuration by default is much more elegant.  I recall now that having the ability to set the redis connection specifically for Sidecloq is intentional though -- there was a use-case where someone wanted to have a different redis instance managing the lock, ie, not the sidekiq redis.

Hopefully the workaround is sufficient for you, but do let me know if you run into issues.  I'll see if I can carve out some time to work on the default configuration, or feel free to send a PR!

**Comment by mattyr** [comment]
So after investigating this a little more, I believe this actually comes down to the size of your custom connection pool.  Sidecloq needs at least one additional connection that it can pull from the pool, and if the pool is too small, it will lock up waiting for that connection.  Try increasing the pool size (there's no harm in doing so, the connections are lazy-created) and see if that works for you.  I'm testing out an update that will check for this condition on bootup and raise an error if there are insufficient connections (in the same way that Sidekiq itself does).

**Comment by tbem** [comment]
After doing some tests, what i'm getting is every time i use the connection pool directly on the Sidekiq config it stops working, even if i use the Sidecloq redis config to use a direct connection to redis instead of using the default config that use the connection from Sidekiq. 
I tried with different pool sizes and can't get it working. 

I took a look at RedisConnection class in Sidekiq, and by default Sidekiq creates a connection pool based on :concurrency or RAILS_MAX_THREADS depending on client/server and some config options: 

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb

If Sidecloq uses this defaults it works fine, and if we look at the connection that it is using with Sidekiq.redis_pool.checkout it is using the redis used for the default ConnectionPool created by Sidekiq.

I just can't figure out why Sidekiq is woking fine with its own connection pool and Sidecloq also, why stops working when the ConnectionPool is passed in config. It should have exactly the same behaviour.

**Comment by mattyr** [comment]
Can I ask what values you have for concurrency, RAILS_MAX_THREADS, and what values you tried for your custom connection pool size?

**Comment by tbem** [comment]
I don't have RAILS_MAX_THREADS configured, my concurrency is 6.

**Comment by mattyr** [comment]
What are you setting your pool size as?

**Comment by tbem** [comment]
I tried with 25, 30.

**Comment by mattyr** [comment]
And that was with the configure_server block?  Hmm.  Should have worked...

**Comment by mattyr** [comment]
Can you try this in your sidecloq configuration:

```ruby
Sidecloq.configure do |config|
  config[:locker_options] = { redis: "your redis connection config" }
end
```

**Comment by tbem** [comment]
Should i update the gem, or this should work with the current version?

**Comment by tbem** [comment]
With the locker options it works, but only if i pass Redis config as an Hash like {url: "redis://0.0.0.0:6379"} instead of a redis client that is the result of Redis.new.

**Comment by mattyr** [comment]
Right, sorry, that hash is the correct way to send the config, not the string.  However, it is bizarre that sending a client via Redis.new isn't working.  We're passing the connection info directly to redlock:

https://github.com/leandromoreira/redlock-rb#redis-client-configuration

Is there a repo I could look at, or could you create a one (or a gist) that replicates the error you're seeing?

**Comment by tbem** [comment]
I can create a gist with the sidekiq configs, but i'm not facing an error. I'm looking at SYSLOG, and looking at the sidekiq/sidecloq logs. This is the scenario where everything is ok:

systemd[1]: Started sidekiq.
TID-gp3v7unoy INFO: Running in ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
TID-gp3v7unoy INFO: See LICENSE and the LGPL-3.0 for licensing details.
TID-gp3v7unoy INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
TID-gp3v7unoy INFO: Starting processing, hit Ctrl-C to stop
TID-gp3vkxhiu Sidecloq INFO: Runner starting
TID-gp3vkxhiu Sidecloq INFO: Obtained leader lock
TID-gp3vkxhiu Sidecloq INFO: Loading schedules into redis

This are the logs when the lock stop working. 

systemd[1]: Started sidekiq.
TID-gp3v7unoy INFO: Running in ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
TID-gp3v7unoy INFO: See LICENSE and the LGPL-3.0 for licensing details.
TID-gp3v7unoy INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
TID-gp3v7unoy INFO: Starting processing, hit Ctrl-C to stop
TID-gp3vkxhiu Sidecloq INFO: Runner starting

Here is a Gist with the configs i'm using: 

https://gist.github.com/tbem/93216bbf12d000bbe227f248b8481bfe

I put some comments on gist, i hope you understand what i mean.

**Comment by mattyr** [comment]
Gotcha.  A replica script/app that reproduces the issue would be *very* helpful; things like gem versions/etc could play a role.

One thing to note is that if you are restarting Sidekiq, it can take a minute for the lock to be released before the next instance can obtain it -- this is normal behavior (default ttl for the lock is 60 seconds).  It'll eventually obtain the lock automatically.

2 more things to try:

- Can you set the pool size to 100?  There isn't any harm in creating a larger pool, as the connections are lazily created.
- If you remove Sidekiq::Status, does it work?
