### ISSUE TITLE
Server time or rails enviroment time?

### ISSUE THREAD

**Issue by nickcoyne** [mattyr/sidecloq#37]
When running inside a rails app, does the scheduler use server time (as cron would), or rails app time (which could be different)?

**Comment by mattyr** [comment]
Hm, I'm not aware of what rails app time is -- can you point me to some docs?

Generally speaking though, the scheduler uses Rufus::Scheduler under the hood, so however that lands on server vs rails app time would be the answer.

I'd be curious what this difference is here though, and if significant, it's probably important for us to document!

**Comment by vanboom** [comment]
INFO:  We have a server in the US Eastern Time Zone.  Sidecloq is triggering the events at the declared time in UTC.
