### ISSUE TITLE
Support for Sidekiq 7

### ISSUE THREAD

**Issue by LouisBoudreau** [mattyr/sidecloq#45]
👋 

Would you consider updating this gem to support [Sidekiq 7](https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-Upgrade.md)?

Thanks!

**Comment by gstokkink** [comment]
I've forked this gem to provide Sidekiq 7 support: https://github.com/bookingexperts/sidecloq/tree/sidekiq-7-support. Been running it in production for a while now, with zero issues. No guarantees though.

**Comment by mattyr** [comment]
@gstokkink interested in opening a PR here?

**Comment by gstokkink** [comment]
Well I've kicked out quite a bit of cruft, including support for Sidekiq < 6.5. I've also dropped ActiveJob support since we don't need it.

**Comment by mattyr** [comment]
ah, i see.  been aiming to support the same versions as sidekiq continues to support, but i believe the sidekiq repo has shifted to a version-branch model making it tricky to maintain compatibility here without switching to a similar setup.

**Comment by mattyr** [comment]
main branch is now compatible with sidekiq >= 6.4!  will release gem shortly.
